library(readr)
StudentsPerformance <- read_csv("Downloads/StudentsPerformance.csv")
View(StudentsPerformance)
install.packages("tidyverse")
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)
head(StudentsPerformance)
summary(StudentsPerformance)
colnames(StudentsPerformance)
namesOfColumns <- c("Gender","Race","Parent_Education","Lunch","Test_Prep","Math_Score","Reading_Score","Writing_Score")
colnames(StudentsPerformance) <- namesOfColumns
table(StudentsPerformance$Gender)
table(StudentsPerformance$Race)
table(StudentsPerformance$Parent_Education)
table(StudentsPerformance$Lunch)
table(StudentsPerformance$Test_Prep)
p <- ggplot(StudentsPerformance, aes(Math_Score)) + geom_histogram(binwidth=5, color="gray", aes(fill=Gender))
p <- p + xlab("Math Scores") + ylab("Gender") + ggtitle("Math Scores by Gender")
p
V1 <- ggplot(StudentsPerformance, aes(Reading_Score)) + geom_histogram(binwidth=5, color="gray", aes(fill=Gender))
V1 <- V1 + xlab("Reading Scores") + ylab("Gender") + ggtitle("Reading Scores by Gender")
V1
V2 <- ggplot(StudentsPerformance, aes(Writing_Score)) +  geom_histogram(binwidth=5, color="gray", aes(fill=Gender))
V2 <- V2 + xlab("Writing Scores") + ylab("Gender") + ggtitle("Writing Scores by Gender")
V2
ggplot(StudentsPerformance, aes(x = Race, fill = Gender)) + geom_bar(position = "stack") + ggtitle("Distribution of Students") + ylab("Students") + xlab("Groups")
ggplot(StudentsPerformance, aes(x = Parent_Education, fill = Gender)) + geom_bar(position = "stack") + ggtitle("Distribution of Students") + ylab("Students") + xlab("Qualification of parent")
